# Generated by Django 2.2.7 on 2019-12-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('port', models.CharField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('process_id', models.IntegerField()),
            ],
            options={
                'db_table': 'hubs',
            },
        ),
    ]
